stages:
  - lint
  - test

eslint:
  stage: lint
  image: node:18
  script:
    - npm install
    - npx eslint .
  only:
    - merge_requests
    - main

unit_tests:
  stage: test
  image: node:18
  script:
    - npm install
    - npx c8 npm test
  only:
    - merge_requests
    - main
