name: Linting and Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (skip scripts to avoid husky error)
        run: npm install --ignore-scripts

      - name: Fix eslint permission
        run: chmod +x ./node_modules/.bin/eslint

      - name: Fix mocha permission
        run: chmod +x ./node_modules/.bin/mocha

      - name: Run ESLint
        run: npx eslint .

      - name: Run Unit Tests
        run: npm test
